### ISSUE TITLE
Demo issue

### ISSUE THREAD

**Issue by kamwal** [euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool#2] opened 2020-05-12 08:59 UTC
During the interp_climatology routine, I encountered the below error. 

`UPDATE_SALINITY_MAPPING: Working on profile  3
Traceback (most recent call last):
  File "L:/users/argo/kamwal/OWC_Python_SSH/owc-software-python/owc_calibration.py", line 73, in <module>
    update_salinity_mapping("/", FLOAT_NAME, USER_CONFIG)
  File "L:\users\argo\kamwal\OWC_Python_SSH\owc-software-python\ow_calibration\update_salinity_mapping\update_salinity_mapping.py", line 356, in update_salinity_mapping
    float_pres)
  File "L:\users\argo\kamwal\OWC_Python_SSH\owc-software-python\ow_calibration\interp_climatology\interp_climatology.py", line 108, in interp_climatology
    delta_pres_min_index = np.nanargmin(abs_delta_pres, axis=0)
  File "<__array_function__ internals>", line 6, in nanargmin
  File "N:\Programs\Anaconda\envs\Project_test\lib\site-packages\numpy\lib\nanfunctions.py", line 501, in nanargmin
    raise ValueError("All-NaN slice encountered")
ValueError: All-NaN slice encountered`

Upon the inspection, I have found all NAN column (column 58). NumPy package can not find the minimum argument for all NAN matrix. 

Float source: 3901960.mat
WMO boxes: wmo_boxes_argo_ctd.mat
config_file:
`
# ===============================
        #
        #    Objective Mapping Parameters
        #

        # max number of historical casts used in objective mapping
        'CONFIG_MAX_CASTS': 300,

        # 1=use PV constraint, 0=don't use PV constraint, in objective mapping
        'MAP_USE_PV': 0,

        # 1=use SAF separation criteria, 0=don't use SAF separation criteria, in objective mapping
        'MAP_USE_SAF': 0,

        # spatial decorrelation scales, in degrees
        'MAPSCALE_LONGITUDE_LARGE': 8,
        'MAPSCALE_LONGITUDE_SMALL': 4,
        'MAPSCALE_LATITUDE_LARGE': 4,
        'MAPSCALE_LATITUDE_SMALL': 2,

        # cross-isobath scales, dimensionless, see BS(2005)
        'MAPSCALE_PHI_LARGE': 0.5,
        'MAPSCALE_PHI_SMALL': 0.1,

        # temporal decorrelation scale, in years
        'MAPSCALE_AGE_LARGE': 20,
        'MAPSCALE_AGE_SMALL': 10,

        # exclude the top xxx dbar of the water column
        'MAP_P_EXCLUDE': 200,

        # only use historical data that are within +/- yyy dbar from float data
        'MAP_P_DELTA': 250
    `

**Comment by edsmall-bodc** [comment] 2020-05-12 09:08
Looks like a dataset from the CTD reference data has no values in it (thanks to @matdon17 for finding this).

For a numpy matrix, if you subtract NaN from a number (eg. 8 - np.nan) it will return NaN. And you're correct, numpy cannot find the minimum of a matrix of all NaNs.

Would a good proposed fix for this to be to check for a column of all NaNs and remove it from the dataset if we encounter it? We could notify the operator of this change.

It is a rare occurence. @matdon17 only found one bad CTD dataset, though a few more argo sets have very few values.

**Comment by matdon17** [comment] 2020-05-12 09:41
Just to note that the Argo reference dataset, where there were multiple occurrences of profiles with a single value, has been corrected in the latest release ARGO_for_DMQC_2020V01 on 11th May.

**Comment by edsmall-bodc** [comment] 2020-05-12 10:54
Fixed and merged in https://git.noc.ac.uk/bodc/owc-software-python/-/merge_requests/27

@kamwal confirmed the fix was worked with the bad dataset

**Closed as completed by edsmall-bodc** 2020-05-12 10:54 UTC
Labels: bug, good first issue
