### ISSUE TITLE
scale_age_small in Python  vs scale_age in Matlab

### ISSUE THREAD

**Issue by kamwal** [euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool#18] opened 2020-06-25 09:09 UTC
In using the map file generated from Matlab I found that it will not work in Python due to different name of the small scale_age.  
This time scale in Matlab are "scale_age" and "scale_age_large" where in Python are "scale_age_small" and "scale_age_large". 

The error message is as follow:

`Traceback (most recent call last):
  File "owc_calibration.py", line 75, in <module>
    update_salinity_mapping("/", FLOAT_NAME, USER_CONFIG)
  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\update_salinity_mapping\update_salinity_mapping.py", line 131, in  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\update_salinity_mapp  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\update_salinity_mapping\update_salinity_mapping.py", line 131, in update_salinity_mapping
    scale_age_small = float_mapped_data['scale_age_small'].flatten()
KeyError: 'scale_age_small'`

WMO: 1901847
Reference data: CTD_for_DMQC_2019V01
WMO boxes: wmo_boxes_ctd.mat
Canfiguration:
`#    Objective Mapping Parameters
        #

        # max number of historical casts used in objective mapping
        'CONFIG_MAX_CASTS': 300,

        # 1=use PV constraint, 0=don't use PV constraint, in objective mapping
        'MAP_USE_PV': 0,

        # 1=use SAF separation criteria, 0=don't use SAF separation criteria, in objective mapping
        'MAP_USE_SAF': 0,

        # spatial decorrelation scales, in degrees
        'MAPSCALE_LONGITUDE_LARGE': 8,
        'MAPSCALE_LONGITUDE_SMALL': 4,
        'MAPSCALE_LATITUDE_LARGE': 4,
        'MAPSCALE_LATITUDE_SMALL': 2,

        # cross-isobath scales, dimensionless, see BS(2005)
        'MAPSCALE_PHI_LARGE': 0.1,
        'MAPSCALE_PHI_SMALL': 0.02,

        # temporal decorrelation scale, in years
        'MAPSCALE_AGE_LARGE': 20,
        'MAPSCALE_AGE_SMALL': 5,

        # exclude the top xxx dbar of the water column
        'MAP_P_EXCLUDE': 100,

        # only use historical data that are within +/- yyy dbar from float data
        'MAP_P_DELTA': 200
    }`

**Comment by apswong** [comment] 2020-06-25 10:34
I like the Python names of "scale_age_large" and "scale_age_small".   @cabanesc (hi Cecile!) didn't rename "scale_age" to "scale_age_small" in Matlab OWC, because the intention was to make the output backward-compatible with the old OW output (which only used a single "scale_age").  For the Python UAT, we can simply do our own rename of "scale_age" to "scale_age_small" in the test input files.  It's not a bug in the Python code.

**Comment by cabanesc** [comment] 2020-06-25 12:26
I agree, we can rename scale_age to scale_age_small in the input file.
Cecile

**Comment by kamwal** [comment] 2020-06-25 12:30
Thank you Annie for clarification. Yes, I agree it is not a bug and I also would prefer  "scale_age_small" instead on only "scale_age".  
I should mention before that I rise that point just to let you and Cecile know about that difference, when you will use the Matlab output in Python code.

**Comment by edsmall-bodc** [comment] 2020-06-26 07:55
Hello! I guess the only foreseeable problem is this: What if someone wants to take an old matlab file and run it through the python version of the calculate_piecewisefit?

I agree that changing it in the matlab version for future files is a good idea, and I understand (for legacy reasons) why you didn't change the variable name when adding the large_scale_age.

What I can do is simply put a try and except clause in the salinity mapping part of the code, ie:

`try:
     small_age = MAPPED_DATA['scale_age_small']
except:
    small_age = MAPPED_DATA['scale_age']
`

This means that, if we fail to find `scale_age_small` in the data set, it will look for `scale_age` instead. This would mean that future run throughs would save things as `scale_age_small`, but we avoid the backwards compatibility issue that we are discussing here. 

A good solution?

**Comment by cabanesc** [comment] 2020-06-26 08:19
Yes, I think it is a very good solution. We could do the same in the matlab version and move to scale_age_small too.

**Comment by edsmall-bodc** [comment] 2020-06-26 08:24
Will make a fix today and show you the branch. @cabanesc, are you okay being the reviewer? Usually I'd suggest checking out the branch, but with such a small change I think you can review by just looking at the code.

**Comment by apswong** [comment] 2020-06-26 08:25
I disagree.  I think the Python code should make a clean break from this legacy issue and insists that users input "scale_age_small" and "scale_age_large".   Instead, we should resolve this legacy issue in Matlab OWC.

**Comment by edsmall-bodc** [comment] 2020-06-26 08:31
@apswong Do you guys keep all the mapped output files for each analysis somewhere? My only concern is that if someone wants to re-calibrate using an old mapped file or something. They may not want to remap the salinity too because the update salinity mapping portion has changed a little over the years, so might yield a slightly different result.

This is a pretty niche situation though. Are you sure you don't want me to add the try clause? I have no problems doing it, but I agree we should change the matlab code!

**Comment by apswong** [comment] 2020-06-26 09:12
Yes, we keep the mapped output files.  If the mapped output file is produced by the old OW mapping, it should contain a single variable "scale_age".  If it is produced by the new OWC mapping, it should contain 2 variables "scale_age_small" and "scale_age_large".  That is one of the main features that distinguishes an OWC map from an OW map.  How the Matlab users manage their mapped output files is up to them to decide.  This is a Matlab OWC legacy issue and should be resolved there, and it is very simple to resolve.  The Python package should focus on producing a clean set of OWC codes, and not propagate old OW legacy any further.  If there are adventurous users who want to do some mixed runs with old outputs, they should know what they are doing - renaming legacy variables is a very simple step, but the awareness is important - they need to know what they are inputing.

**Comment by apswong** [comment] 2020-06-26 09:13
@cabanesc  and @apswong  should sort this out in OWC Matlab.

**Comment by edsmall-bodc** [comment] 2020-06-26 09:31
@apswong Would you like me to create an issue in the matlab repo?

**Comment by apswong** [comment] 2020-06-26 09:43
I would ask @cabanesc  if she wants that logged as an issue in the matlab repo.  I'm not much of a Github, or Git, person.  But I made a big note of it in my list of things to do, in pen and paper ;)

**Comment by cabanesc** [comment] 2020-06-26 09:50
I agree that we need to solve this problem in the OWC matlab.  @edsmall-bodc  can add an issue in the matlab repo

**Comment by edsmall-bodc** [comment] 2020-06-26 10:31
Closing this issue, as we have assessed that this is a matlab legacy issue, not a python one.

**Closed as completed by edsmall-bodc** 2020-06-26 10:31 UTC
